export default country = [
  'USA',
  'Brazil',
  'Russia',
  'Spain',
  'UK',
  'Italy',
  'France',
  'Germany',
  'Turkey',
  'India',
  'Iran',
  'Peru',
  'Canada',
  'China',
  'Chile',
  'Saudi Arabia',
  'Mexico',
  'Pakistan',
  'Belgium',
  'Qatar',
  'Netherlands',
  'Belarus',
  'Ecuador',
  'Bangladesh',
  'Sweden',
  'Singapore',
  'UAE',
  'Portugal',
  'Switzerland',
  'Ireland',
  'South Africa',
  'Indonesia',
  'Colombia',
  'Kuwait',
  'Poland',
  'Ukraine',
  'Egypt',
  'Romania',
  'Israel',
  'Japan',
  'Austria',
  'Dominican Republic',
  'Philippines',
  'Argentina',
  'Afghanistan',
  'Panama',
  'Denmark',
  'S. Korea',
  'Serbia',
  'Bahrain',
  'Kazakhstan',
  'Czechia',
  'Algeria',
  'Norway',
  'Nigeria',
  'Oman',
  'Armenia',
  'Malaysia',
  'Morocco',
  'Moldova',
  'Australia',
  'Bolivia',
  'Ghana',
  'Finland',
  'Cameroon',
  'Iraq',
  'Azerbaijan',
  'Honduras',
  'Luxembourg',
  'Sudan',
  'Guatemala',
  'Hungary',
  'Uzbekistan',
  'Guinea',
  'Tajikistan',
  'Senegal',
  'Thailand',
  'Greece',
  'Ivory Coast',
  'Djibouti',
  'Bulgaria',
  'Bosnia and Herzegovina',
  'DRC',
  'Croatia',
  'Gabon',
  'El Salvador',
  'North Macedonia',
  'Cuba',
  'Estonia',
  'Iceland',
  'Somalia',
  'Lithuania',
  'Mayotte',
  'Kyrgyzstan',
  'Slovakia',
  'New Zealand',
  'Slovenia',
  'Maldives',
  'Kenya',
  'Sri Lanka',
  'Venezuela',
  'Guinea-Bissau',
  'Haiti',
  'Lebanon',
  'Mali',
  'Hong Kong',
  'Latvia',
  'Tunisia',
  'Equatorial Guinea',
  'Albania',
  'Costa Rica',
  'Niger',
  'Cyprus',
  'Zambia',
  'Paraguay',
  'Burkina Faso',
  'South Sudan',
  'Uruguay',
  'Nepal',
  'Andorra',
  'Nicaragua',
  'Sierra Leone',
  'Georgia',
  'Jordan',
  'Diamond Princess',
  'Ethiopia',
  'Chad',
  'CAR',
  'San Marino',
  'Malta',
  'Madagascar',
  'Jamaica',
  'Channel Islands',
  'Tanzania',
  'Congo',
  'Réunion',
  'Sao Tome and Principe',
  'Taiwan',
  'Palestine',
  'Togo',
  'Cabo Verde',
  'French Guiana',
  'Rwanda',
  'Isle of Man',
  'Mauritius',
  'Vietnam',
  'Montenegro',
  'Mauritania',
  'Liberia',
  'Eswatini',
  'Uganda',
  'Yemen',
  'Mozambique',
  'Benin',
  'Myanmar',
  'Martinique',
  'Faeroe Islands',
  'Guadeloupe',
  'Gibraltar',
  'Mongolia',
  'Brunei',
  'Guyana',
  'Bermuda',
  'Cayman Islands',
  'Cambodia',
  'Syria',
  'Trinidad and Tobago',
  'Malawi',
  'Aruba',
  'Bahamas',
  'Monaco',
  'Barbados',
  'Comoros',
  'Liechtenstein',
  'Sint Maarten',
  'Libya',
  'Angola',
  'French Polynesia',
  'Zimbabwe',
  'Macao',
  'Burundi',
  'Saint Martin',
  'Eritrea',
  'Botswana',
  'Bhutan',
  'Antigua and Barbuda',
  'Gambia',
  'Timor-Leste',
  'Grenada',
  'Namibia',
  'Laos',
  'Belize',
  'Curaçao',
  'Fiji',
  'New Caledonia',
  'Saint Lucia',
  'St. Vincent Grenadines',
  'Dominica',
  'Saint Kitts and Nevis',
  'Falkland Islands',
  'Turks and Caicos',
  'Greenland',
  'Vatican City',
  'Montserrat',
  'Suriname',
  'Seychelles',
  'MS Zaandam',
  'Western Sahara',
  'British Virgin Islands',
  'Papua New Guinea',
  'Caribbean Netherlands',
  'St. Barth',
  'Anguilla',
  'Lesotho',
  'Saint Pierre Miquelon',
];
